apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-destination-api-audit
  namespace: argocd-project-manager
  labels:
    app: argocd-destination-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment and set storageClassName if you need a specific storage class
  # storageClassName: standard
