apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-destination-api
  # RoleBinding must be in the same namespace as the Role
  namespace: argocd
  labels:
    app: argocd-destination-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-destination-api
subjects:
  - kind: ServiceAccount
    name: argocd-destination-api
    # ServiceAccount is in the argocd-project-manager namespace
    namespace: argocd-project-manager
